

services:
  mongo:
    image: mongo:7
    container_name: mongo
    command: ["--replSet", "rs0", "--bind_ip_all"]  # RS de 1 nodo + bind a 0.0.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d  # scripts .js/.sh para seed
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand({ ping: 1 })' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  # Inicializa el replica set (una sola vez)
  mongo-rs-init:
    image: mongo:7
    container_name: mongo-rs-init
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: >
      bash -lc "
      mongosh --host mongo:27017 --eval '
        try { rs.initiate({_id:\"rs0\", members:[{_id:0, host:\"mongo:27017\"}]}); } catch(e) { print(e); }
        rs.status();
      '
      "
    restart: "no"

  # UI opcional
  mongo-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    restart: unless-stopped

volumes:
  mongo_data:
